Iphone/urls.py
from django.conf.urls import url

from Iphone import views
app_name = 'Iphone'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r"^test/j/$",views.test,name='test'),
    url(r'^register/$',views.register),
    url(r'^login/$',views.login),
    url(r'^logout/$',views.logout),
    url(r'^cart/$',views.cart),

]

project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('Iphone.urls')),
]

Iphone/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=80)
    password = models.CharField(max_length=256)
    tel = models.CharField(max_length=20)

Iphone/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from Iphone.models import User


def index(request):
    username = request.COOKIES.get('username')
    return render(request,'index.html',context={'username':username})


def test(request):
    return HttpResponse('测试数据，反向解析操作')

# 注册
def register(request):
    if request.method == 'GET':
        return render(request,'register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        tel = request.POST.get('tel')
        print(username,password,tel)

        user = User()
        user.username = username
        user.password = password
        user.tel = tel
        user.save()

        response = redirect('Iphone:index')

        response.set_cookie('username',username)

        return response

# 登录
def login(request):
    if request.method == 'GET':
        return render(request,'login.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(username,password)

        users = User.objects.filter(username=username,password=password)
        if users.count():
            user = users.first()

            response = redirect('Iphone:index')

            response.set_cookie('username',user.username)

            return response
        else:
            return HttpResponse('账号或密码错误！！')


def logout(request):

    response = redirect('Iphone:index')

    response.delete_cookie('username')

    return response


def cart(request):
    username = request.COOKIES.get('username')
    return render(request, 'cart.html', context={'username': username})

templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
</head>
<body>
<h1>
    {% if username %}
        {{ username }} 的购物车
    {% else %}
        你还没登录，请 <a href="/login/">登录</a>
    {% endif %}
</h1>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>

<a href="{% url 'Iphone:test' %}"> 测试1</a>

<hr>
{% if username %}
    <h1>用户名: {{ username }}</h1>
{% else %}
    <h1>你还没登录，请 <a href="/login/">登录</a></h1>
{% endif %}
<p>
    <a href="/register/">注册</a>
</p>
<p>
    <a href="/login/">登录</a>
</p>
<p>
    <a href="/logout/">退出登录</a>
</p>
<p>
    <a href="/cart/">购物车</a>
</p>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>

<form action="/login/" method="post">
    {% csrf_token %}
    <p>
        账号: <input type="text" name="username">
    </p>
    <p>
        密码: <input type="password" name="password">
    </p>
    <input type="submit" value="登录">
</form>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    <form action="/register/" method="post">
        {% csrf_token %}
        <p>
            账号: <input type="text" name="username">
        </p>
        <p>
            密码： <input type="password" name="password">
        </p>
        <p>
            手机： <input type="text" name="tel">
        </p>
        <input type="submit" value="注册">
    </form>
</body>
</html>